=== jonnyfromralphs/Solvd-JDBC/src/main/resources/User.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="username" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="registration_date" type="xs:date"/>
                            <xs:element name="addresses">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="address" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="address_line1" type="xs:string"/>
                                                    <xs:element name="address_line2" type="xs:string"/>
                                                    <xs:element name="city" type="xs:string"/>
                                                    <xs:element name="state" type="xs:string"/>
                                                    <xs:element name="zip_code" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jonnyfromralphs/Solvd-JDBC/src/main/resources/User.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="User.xsd">
    <user>
        <username>johndoe</username>
        <email>johndoe@example.com</email>
        <password>password123</password>
        <registration_date>2023-06-12</registration_date>
    </user>
    <user>
        <username>janedoe</username>
        <email>janedoe@example.com</email>
        <password>pass4321</password>
        <registration_date>2023-06-10</registration_date>
    </user>
</users>
